export const createTRWithTemplatesHelpSteps = [
  {
    id: 'welcome-create',
    target: '[data-help-id="page-title"]',
    title: 'Criar TR com Template',
    content: 'Vamos guiá-lo pelo processo de criação de um Termo de Referência usando templates e IA. Siga cada passo com atenção!',
    placement: 'bottom' as const,
  },
  {
    id: 'progress-guide',
    target: '[data-help-id="progress-indicator"]',
    title: 'Suas 5 Etapas',
    content: 'A criação está dividida em 5 etapas: 1) Informações Gerais, 2) Especificações, 3) Critérios, 4) Cronograma, 5) Revisão. Você pode navegar entre elas livremente.',
    placement: 'bottom' as const,
  },
  {
    id: 'template-selection',
    target: '[data-help-id="field-template"]',
    title: 'Passo 1: Escolher um Template',
    content: 'IMPORTANTE: Comece selecionando um template! Ele vai preencher automaticamente vários campos, economizando muito tempo e garantindo padronização.',
    placement: 'bottom' as const,
  },
  {
    id: 'template-benefits',
    target: '[data-help-id="field-template"]',
    title: 'Por Que Usar Templates?',
    content: 'Templates contêm: campos pré-preenchidos, sugestões de texto, estruturas validadas e boas práticas. Você sempre pode editar tudo depois!',
    placement: 'bottom' as const,
  },
  {
    id: 'ai-generation',
    target: '[data-help-id="ai-generate-button"]',
    title: 'IA para Gerar Conteúdo',
    content: 'Depois de escolher um template, você pode usar a IA! Ela analisa o template e gera conteúdo personalizado baseado no seu contexto específico.',
    placement: 'left' as const,
  },
  {
    id: 'ai-how-works',
    target: '[data-help-id="ai-generate-button"]',
    title: 'Como a IA Funciona?',
    content: 'A IA lê o template, entende a estrutura esperada e gera conteúdo profissional para todos os campos. Você pode fornecer contexto adicional (área, orçamento, prazo) para melhorar os resultados.',
    placement: 'left' as const,
  },
  {
    id: 'manual-edit',
    target: '[data-help-id="field-title"]',
    title: 'Edição Manual',
    content: 'Mesmo usando template e IA, você pode editar qualquer campo manualmente. O sistema valida em tempo real e mostra se o preenchimento está correto.',
    placement: 'bottom' as const,
  },
  {
    id: 'field-validation',
    target: '[data-help-id="field-title"]',
    title: 'Validação Automática',
    content: 'Campos obrigatórios são marcados com * (asterisco). O sistema mostra ícones de sucesso ✓ quando o campo está válido e mensagens de erro quando algo está incorreto.',
    placement: 'bottom' as const,
  },
  {
    id: 'type-matters',
    target: '[data-help-id="field-type"]',
    title: 'Tipo de Contratação',
    content: 'O tipo (Produto, Serviço, Consultoria, etc.) determina quais campos serão obrigatórios e que tipo de conteúdo a IA irá gerar. Escolha com cuidado!',
    placement: 'bottom' as const,
  },
  {
    id: 'autosave-feature',
    target: '[data-help-id="autosave-indicator"]',
    title: 'Salvamento Automático',
    content: 'Não se preocupe em perder seu trabalho! O sistema salva automaticamente a cada 30 segundos. Você pode sair e voltar depois sem problemas.',
    placement: 'bottom' as const,
  },
  {
    id: 'guided-tour',
    target: '[data-help-id="help-drawer"]',
    title: 'Ajuda Sempre Disponível',
    content: 'Clique no ícone de ajuda (?) a qualquer momento para rever este tour, acessar FAQs ou obter suporte. Você não está sozinho!',
    placement: 'left' as const,
  },
  {
    id: 'next-step-action',
    target: '[data-help-id="next-button"]',
    title: 'Avançar Entre Etapas',
    content: 'Quando terminar de preencher os campos obrigatórios, clique aqui para avançar para a próxima etapa. Você pode voltar a qualquer momento!',
    placement: 'top' as const,
  },
];
