export const createTRHelpSteps = [
  {
    id: 'welcome',
    target: '[data-help-id="page-title"]',
    title: 'Bem-vindo ao Sistema de TRs!',
    content: 'Vamos guiá-lo pelo processo de criação de um Termo de Referência. Este tour mostrará cada etapa do processo.',
    placement: 'bottom' as const,
  },
  {
    id: 'progress',
    target: '[data-help-id="progress-indicator"]',
    title: 'Indicador de Progresso',
    content: 'Aqui você pode ver em qual etapa está e navegar entre as etapas já preenchidas.',
    placement: 'bottom' as const,
  },
  {
    id: 'title',
    target: '[data-help-id="field-title"]',
    title: 'Título do TR',
    content: 'Digite um título descritivo para o seu Termo de Referência. Mínimo de 10 caracteres.',
    placement: 'bottom' as const,
  },
  {
    id: 'type',
    target: '[data-help-id="field-type"]',
    title: 'Tipo de Contratação',
    content: 'Selecione o tipo de contratação que melhor se adequa ao seu projeto.',
    placement: 'bottom' as const,
  },
  {
    id: 'template',
    target: '[data-help-id="field-template"]',
    title: 'Templates',
    content: 'Selecione um template para preencher automaticamente vários campos com valores predefinidos.',
    placement: 'bottom' as const,
  },
  {
    id: 'description',
    target: '[data-help-id="field-description"]',
    title: 'Descrição',
    content: 'Descreva detalhadamente o objeto da contratação. Mínimo de 50 caracteres.',
    placement: 'top' as const,
  },
  {
    id: 'objective',
    target: '[data-help-id="field-objective"]',
    title: 'Objetivo',
    content: 'Defina claramente os objetivos que devem ser alcançados com esta contratação. Mínimo de 30 caracteres.',
    placement: 'top' as const,
  },
  {
    id: 'autosave',
    target: '[data-help-id="autosave-indicator"]',
    title: 'Salvamento Automático',
    content: 'O sistema salva automaticamente suas alterações a cada 30 segundos. Você verá o status aqui.',
    placement: 'bottom' as const,
  },
  {
    id: 'next-button',
    target: '[data-help-id="next-button"]',
    title: 'Avançar para Próxima Etapa',
    content: 'Quando terminar de preencher os dados obrigatórios, clique aqui para avançar para a próxima etapa.',
    placement: 'top' as const,
  },
];
