export const templatesHelpSteps = [
  {
    id: 'welcome-templates',
    target: '[data-help-id="templates-title"]',
    title: 'Biblioteca de Templates',
    content: 'Bem-vindo à Biblioteca de Templates! Aqui você encontra modelos pré-configurados para criar Termos de Referência de forma rápida e padronizada.',
    placement: 'bottom' as const,
  },
  {
    id: 'what-are-templates',
    target: '[data-help-id="templates-hero"]',
    title: 'O que são Templates?',
    content: 'Templates são modelos prontos com campos pré-preenchidos. Eles economizam tempo e garantem que você não esqueça nenhuma informação importante ao criar um TR.',
    placement: 'bottom' as const,
  },
  {
    id: 'filter-search',
    target: '[data-help-id="templates-filters"]',
    title: 'Buscar e Filtrar Templates',
    content: 'Use a busca para encontrar templates por nome ou descrição. Filtre por categoria (Consultoria, Obras, etc.) e tipo (Produto, Serviço) para encontrar exatamente o que precisa.',
    placement: 'bottom' as const,
  },
  {
    id: 'template-card',
    target: '[data-help-id="template-card-0"]',
    title: 'Detalhes do Template',
    content: 'Cada card mostra: título, descrição, categoria, tipo, última atualização e número de downloads. Isso ajuda você a escolher o melhor template para sua necessidade.',
    placement: 'top' as const,
  },
  {
    id: 'use-template',
    target: '[data-help-id="use-template-0"]',
    title: 'Usar Template',
    content: 'Clique em "Usar Template" para ser direcionado à criação de um novo TR com os campos pré-preenchidos deste template. Você poderá editar tudo depois!',
    placement: 'top' as const,
  },
  {
    id: 'download-template',
    target: '[data-help-id="download-template-0"]',
    title: 'Download do Arquivo',
    content: 'Baixe o arquivo original do template para usar como referência, compartilhar com colegas ou importar para outros sistemas.',
    placement: 'top' as const,
  },
  {
    id: 'upload-new',
    target: '[data-help-id="upload-template-button"]',
    title: 'Criar Novo Template',
    content: 'Clique aqui para fazer upload de um novo template. Você pode criar templates personalizados para sua equipe reutilizar!',
    placement: 'left' as const,
  },
  {
    id: 'how-upload-works',
    target: '[data-help-id="upload-template-button"]',
    title: 'Como Funciona o Upload?',
    content: 'Ao criar um template você precisa: 1) Escolher um arquivo (Word, Excel, PDF), 2) Preencher título e descrição, 3) Selecionar categoria e tipo, 4) Decidir se será público ou privado.',
    placement: 'left' as const,
  },
  {
    id: 'storage-info',
    target: '[data-help-id="templates-filters"]',
    title: 'Armazenamento Seguro',
    content: 'Todos os templates são armazenados de forma segura na nuvem. Templates públicos ficam disponíveis para todos, enquanto templates privados só você pode acessar.',
    placement: 'bottom' as const,
  },
  {
    id: 'next-steps',
    target: '[data-help-id="use-template-0"]',
    title: 'Próximos Passos',
    content: 'Agora que você conhece os templates, experimente usar um para criar seu primeiro TR! O sistema irá preencher automaticamente vários campos, economizando muito tempo.',
    placement: 'top' as const,
  },
];
